/**
 * @fileoverview MSW (Mock Service Worker) handler generator
 * @module formatters/msw
 */

/**
 * @typedef {Object} MSWOptions
 * @property {string} name - Fixture name
 * @property {string} url - API URL
 * @property {string} method - HTTP method
 */

/**
 * Extract pathname from a URL string (absolute or relative)
 * @param {string} url - URL string
 * @returns {string} pathname
 */
function extractPath(url) {
  try {
    return new URL(url).pathname;
  } catch {
    return url.startsWith('/') ? url : `/${url}`;
  }
}

/**
 * Generate MSW handler code
 * @param {MSWOptions} options - Handler options
 * @returns {string} Generated MSW handler code
 */
export function generateMSW(options) {
  const { name, url, method = 'GET' } = options;
  const urlPath = extractPath(url);
  const lowerMethod = method.toLowerCase();
  const handlerName = `${name}Handler`;

  return `/**
 * MSW Handler for ${name}
 * Auto-generated by apitape
 * @module fixtures/${name}.msw
 */

import { createRequire } from 'node:module';
import { http, HttpResponse } from 'msw';

const require = createRequire(import.meta.url);
const ${name}Fixture = require('./${name}.json');

/**
 * MSW handler for ${method} ${urlPath}
 * @type {import('msw').HttpHandler}
 */
export const ${handlerName} = http.${lowerMethod}('${urlPath}', () => {
  return HttpResponse.json(${name}Fixture);
});

export default ${handlerName};
`;
}

/**
 * Generate MSW handler for multiple fixtures
 * @param {Array<MSWOptions>} fixtures - Fixture list
 * @returns {string} Combined handlers code
 */
export function generateMSWHandlers(fixtures) {
  const imports = [
    `import { createRequire } from 'node:module';`,
    `import { http, HttpResponse } from 'msw';`,
    ``,
    `const require = createRequire(import.meta.url);`
  ];

  const fixtureRequires = [];
  const handlers = [];

  for (const fixture of fixtures) {
    const { name, url, method = 'GET' } = fixture;
    const urlPath = extractPath(url);

    fixtureRequires.push(`const ${name}Fixture = require('./${name}.json');`);

    handlers.push(`  http.${method.toLowerCase()}('${urlPath}', () => {
    return HttpResponse.json(${name}Fixture);
  })`);
  }

  return `/**
 * MSW Handlers - Auto-generated by apitape
 * @module fixtures/handlers
 */

${imports.join('\n')}
${fixtureRequires.join('\n')}

export const handlers = [
${handlers.join(',\n')}
];

export default handlers;
`;
}
