/**
 * @fileoverview MSW (Mock Service Worker) handler generator
 * @module formatters/msw
 */

/**
 * @typedef {Object} MSWOptions
 * @property {string} name - Fixture name
 * @property {string} url - API URL
 * @property {string} method - HTTP method
 * @property {Object} [headers] - Request headers
 */

/**
 * Generate MSW handler code
 * @param {MSWOptions} options - Handler options
 * @returns {string} Generated MSW handler code
 */
export function generateMSW(options) {
  const { name, url, method = 'GET' } = options;

  // Extract path from URL
  let path;
  try {
    const urlObj = new URL(url);
    path = urlObj.pathname;
  } catch {
    // If relative URL, use as-is
    path = url.startsWith('/') ? url : `/${url}`;
  }

  const lowerMethod = method.toLowerCase();
  const handlerName = `${name}Handler`;
  const fixtureImport = `./${name}.json`;

  const code = `/**
 * MSW Handler for ${name}
 * Auto-generated by mock-api-fixtures
 * @module fixtures/${name}.msw
 */

import { http, HttpResponse } from 'msw';
import ${name}Fixture from '${fixtureImport}' assert { type: 'json' };

/**
 * MSW handler for ${method} ${path}
 * @type {import('msw').HttpHandler}
 */
export const ${handlerName} = http.${lowerMethod}('${path}', () => {
  return HttpResponse.json(${name}Fixture);
});

export default ${handlerName};
`;

  return code;
}

/**
 * Generate MSW handler for multiple fixtures
 * @param {Array<{name: string, url: string, method: string}>} fixtures - Fixture list
 * @returns {string} Combined handlers code
 */
export function generateMSWHandlers(fixtures) {
  const imports = [
    `import { http, HttpResponse } from 'msw';`
  ];

  const handlers = [];

  for (const fixture of fixtures) {
    const { name, url, method = 'GET' } = fixture;

    let path;
    try {
      const urlObj = new URL(url);
      path = urlObj.pathname;
    } catch {
      path = url.startsWith('/') ? url : `/${url}`;
    }

    imports.push(`import ${name}Fixture from './${name}.json' assert { type: 'json' };`);

    handlers.push(`  http.${method.toLowerCase()}('${path}', () => {
    return HttpResponse.json(${name}Fixture);
  })`);
  }

  const code = `/**
 * MSW Handlers - Auto-generated by mock-api-fixtures
 * @module fixtures/handlers
 */

${imports.join('\n')}

export const handlers = [
${handlers.join(',\n')}
];

export default handlers;
`;

  return code;
}

/**
 * Save MSW handler to file
 * @param {string} name - Fixture name
 * @param {MSWOptions} options - Handler options
 * @param {string} fixturesDir - Fixtures directory
 * @returns {Promise<string>} File path
 */
export async function saveMSWHandler(name, options, fixturesDir = './fixtures') {
  const fs = await import('fs/promises');
  const path = await import('path');

  const code = generateMSW({ name, ...options });
  const filePath = path.join(fixturesDir, `${name}.msw.js`);

  await fs.writeFile(filePath, code, 'utf-8');

  return filePath;
}